# Generated by Django 2.2.5 on 2019-10-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LBook', '0013_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acheivement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered', models.CharField(max_length=30)),
                ('skilledYouth', models.CharField(max_length=30)),
                ('tPs', models.CharField(max_length=30)),
                ('employers', models.CharField(max_length=30)),
                ('institutes', models.CharField(max_length=30)),
                ('collaborations', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='update',
            name='link',
            field=models.CharField(default='#', max_length=500),
        ),
    ]
