# Generated by Django 2.2.5 on 2019-10-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LBook', '0014_auto_20191001_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/board/')),
                ('name', models.CharField(max_length=30)),
                ('depts', models.CharField(max_length=30)),
                ('desig_apssdc', models.CharField(max_length=30)),
            ],
        ),
    ]
