# Generated by Django 2.2.5 on 2019-10-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LBook', '0015_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(default='Active', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='update',
            name='status',
            field=models.CharField(default='Active', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='director',
            name='depts',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
