# Generated by Django 2.2.5 on 2019-10-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LBook', '0016_auto_20191001_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='status',
        ),
        migrations.AddField(
            model_name='update',
            name='tatus',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'InActive')], default='active', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'InActive')], max_length=9),
        ),
    ]
