# Generated by Django 2.1.3 on 2019-10-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LBook', '0017_auto_20191001_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('srikakulam', 'Srikakulam'), ('vizinagaram', 'Vizinagaram'), ('visakapatnam', 'Visakapatnam'), ('eastGodavari', 'East Godavari'), ('krishna', 'Krishna'), ('westGodavari', 'West Godavari'), ('guntur', 'Guntur'), ('prakasam', 'Prakasam'), ('nellore', 'Nellore'), ('chittoor', 'Chittoor'), ('kadapa', 'Kadapa'), ('ananthapur', 'Ananthapur'), ('kurnool', 'Kurnool')], max_length=300)),
                ('name', models.CharField(max_length=600)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='update',
            old_name='tatus',
            new_name='status',
        ),
    ]
