# Generated by Django 2.1.3 on 2019-10-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LBook', '0018_auto_20191002_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=600)),
                ('image', models.ImageField(upload_to='static/images/gallery/')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
