# Generated by Django 2.1.3 on 2019-10-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LBook', '0019_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='hide_show',
            field=models.CharField(choices=[('hide', 'Hide'), ('show', 'Show')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
